#!/bin/sh
set -x

nasm -felf32 boot.asm -o boot.o
nasm -felf32 boot2.asm -o boot2.o
ld -m elf_i386 -n -o kernel.bin -T linker.ld boot.o boot2.o

qemu-system-i386 -kernel kernel.bin
exit


GRUB_CONFIG='isodir/boot/grub/grub.cfg'

cargo build

# grub-file --is-x86-multiboot myos.bin || echo 'fail check'

mkdir -p isodir/boot/grub
cat << EOF > "${GRUB_CONFIG}"
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by magic
#
set timeout=5

menuentry "myos" {
    multiboot2 /boot/myos.bin
}
EOF
if test -e /boot/memtest86+.bin; then
  cp /boot/memtest86+.bin isodir/boot/
  cat << EOF >> "${GRUB_CONFIG}"
menuentry "Memory test (memtest86+, serial console 115200)" {
    linux16 /boot/memtest86+.bin console=ttyS0,115200n8
}
EOF
fi

grub-mkrescue -o myos.iso isodir
